### ISSUE TITLE
Bitbucket repository still available ? 

### ISSUE THREAD

**Issue by sheikhasim** [MBradbury/slp#16]
Anonymously:

:::bash hg clone https://MBradbury@bitbucket.org/MBradbury/slp-algorithms-tinyos
I'm not able to fork/clone the repo.
Please respond asap.
Thanks.

**Comment by MBradbury** [comment]
No it is not. You will need to use this repository instead.

**Comment by sheikhasim** [comment]
So shouldn't the setup instructions change then. I'm trying to setup this for my final year project.

**Comment by MBradbury** [comment]
Feel free to send a pull request. I do not use this code currently, so it is not maintained or supported.
